#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "EIoTK_Activity_02"
  https://create.arduino.cc/cloud/things/eeb745e3-8a83-499b-94f5-b198740e4199

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float temperature;
  CloudPressure pSI;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier carrier;

void setup() {
  // Initialize serial
  Serial.begin(9600);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  CARRIER_CASE = true;
  carrier.begin();

  //Get Cloud Info/errors , 0 (only errors) up to 4
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();

  
  while (ArduinoCloud.connected() != 1) {
    ArduinoCloud.update();
    carrier.display.setTextSize(5);
    carrier.Pressure.readPressure();
    carrier.display.setCursor(20, 70);
    carrier.display.println("epal");
    carrier.display.setCursor(5, 110);
    carrier.display.println("kastoria");
    delay(500);
  }

}

void loop() {
  ArduinoCloud.update();
  // Your code here
  }
  temperature = carrier.Env.readTemperature();
  humidity = carrier.Env.readHumidity();
  Serial.print(temperature);
  Serial.print(",");
  Serial.println(humidity);
  Serial.print(coloredlight)
  delay(1000);
}



/*
  Since PSI is READ_WRITE variable, onPSIChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPSIChange()  {
  // Add your code here to act upon PSI change
}








/*
  Since Coloredlight is READ_WRITE variable, onColoredlightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onColoredlightChange()  {
  // Add your code here to act upon Coloredlight change
}

